Repository JiyaGupta-cs/ShopNex, pull requests merged in 2024-06, with the labels that each got.

#342 Fixed footer logo link
  src/Components/Footer/Footer.jsx
Labels: GSSOC, level 1

#336 Update contributing.md
  contributing.md
Labels: easy, GSSOC

#331 Resolved the Email Validation problem
  src/Components/NewsLetter/NewsLetter.css
  src/Components/NewsLetter/NewsLetter.jsx
Labels: GSSOC, level 1

#252 Item added to cart
  package-lock.json
  package.json
  src/Components/ProductDisplay/ProductDisplay.jsx
Labels: GSSOC, level 2

#235 APPERANCE OF NAVBAR DIVS #222
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.jsx
Labels: GSSOC, level 1

#334 feat/ update-card-UI
  package-lock.json
  package.json
  src/Components/Item/Item.jsx
  src/index.css
  tailwind.config.js
Labels: GSSOC, level 2

#344 Added the review section component to the product page.
  package-lock.json
  package.json
  src/Components/ReviewSection/ReviewSection.css
  src/Components/ReviewSection/ReviewSection.jsx
  src/Pages/Product.jsx
Labels: GSSOC, level 2

#348 Added Scroll to top in about and contact us
  src/Components/Footer/Footer.jsx
Labels: GSSOC, level 1

#242 Not Found Functionality added
  src/App.js
  src/Pages/CSS/NotFound.css
  src/Pages/NotFound.jsx
Labels: GSSOC, level 2
